/* map_act1_trainingyard.c -- Bouillon castle training yard (Act 1 opening).
 * Art: graphics/a1_tiles.png (grit); layout and collision:
 * map_act1_layout.c, both generated by tools/gen_act1_art.py. */
#include <tonc.h>
#include "map.h"
#include "audio.h"
#include "a1_tiles.h"
#include "map_act1_layout.h"

const MapHeader g_mapAct1TrainingYard = {
    .widthMeta = A1_MAP_W,
    .heightMeta = A1_MAP_H,
    .metatileLayer = g_a1MetaLayer,
    .collisionFlags = g_a1Collision,
    .tilesetGfx = (const u16 *)a1_tilesTiles,
    .tilesetGfxLen = a1_tilesTilesLen / 2,
    .tilesetPal = a1_tilesPal,
    .metaSheetMap = a1_tilesMap,
    .metaSheetCols = A1_SHEET_COLS,
    .encounterTableId = 0,
    .scriptEntryId = 0,
    .bgmId = AUDIO_BGM_NONE
};
