/* map_prelude1.c -- Church of the Holy Sepulchre courtyard (prelude
 * vignette 1). Art: graphics/p1_tiles.png (grit); layout and collision:
 * map_prelude1_layout.c, both generated by tools/gen_prelude1_art.py. */
#include <tonc.h>
#include "map.h"
#include "audio.h"
#include "p1_tiles.h"
#include "map_prelude1_layout.h"

const MapHeader g_mapPrelude1Courtyard = {
    .widthMeta = P1_MAP_W,
    .heightMeta = P1_MAP_H,
    .metatileLayer = g_p1MetaLayer,
    .collisionFlags = g_p1Collision,
    .tilesetGfx = (const u16 *)p1_tilesTiles,
    .tilesetGfxLen = p1_tilesTilesLen / 2,
    .tilesetPal = p1_tilesPal,
    .metaSheetMap = p1_tilesMap,
    .metaSheetCols = P1_SHEET_COLS,
    .encounterTableId = 0,
    .scriptEntryId = 0,
    .bgmId = AUDIO_BGM_NONE
};
