/* Generated by tools/gen_prelude1_art.py -- do not edit. */
#ifndef CRUSADE_MAP_PRELUDE1_LAYOUT_H
#define CRUSADE_MAP_PRELUDE1_LAYOUT_H

#include <tonc_types.h>

#define P1_MAP_W 30
#define P1_MAP_H 20
#define P1_META_COUNT 64
#define P1_SHEET_COLS 8

extern const u16 g_p1MetaLayer[P1_MAP_W * P1_MAP_H];
extern const u8  g_p1Collision[P1_META_COUNT];

#endif
