/* Generated by tools/gen_act1_art.py -- do not edit. */
#ifndef CRUSADE_MAP_ACT1_LAYOUT_H
#define CRUSADE_MAP_ACT1_LAYOUT_H

#include <tonc_types.h>

#define A1_MAP_W 20
#define A1_MAP_H 15
#define A1_META_COUNT 51
#define A1_SHEET_COLS 8

extern const u16 g_a1MetaLayer[A1_MAP_W * A1_MAP_H];
extern const u8  g_a1Collision[A1_META_COUNT];

#endif
