/* text_ids.h -- indices into g_textBank[], shared by every scene script
 * table so chapters can't collide on raw integers.
 */
#ifndef CRUSADE_TEXT_IDS_H
#define CRUSADE_TEXT_IDS_H

enum {
    /* Opening cinematic (src/intro.c) */
    TEXT_INTRO_YEAR = 0,
    TEXT_INTRO_SELJUKS,
    TEXT_INTRO_ALEXIOS,
    TEXT_INTRO_CLERMONT,
    TEXT_INTRO_DEUS_VULT,
    TEXT_INTRO_GODFREY,
    TEXT_INTRO_PLEDGE,
    TEXT_INTRO_MARCH,
    TEXT_INTRO_ROAD,
    TEXT_INTRO_BEGIN,

    /* Prelude 1: Jerusalem courtyard */
    TEXT_P1_INTRO,
    TEXT_P1_INTRO_CROWD,
    TEXT_P1_MEET_GUIDE,
    TEXT_P1_MEET_THEO,
    TEXT_P1_MEET_GUIDE2,
    TEXT_P1_MEET_SILVANUS,
    TEXT_P1_MEET_ANNA,
    TEXT_P1_MEET_GUIDE3,
    TEXT_P1_TUTORIAL_MOVE,
    TEXT_P1_TUTORIAL_HERD,
    TEXT_P1_THEO_WELL,
    TEXT_P1_HINT_RECALL,
    TEXT_P1_RECALL1_GUIDE,
    TEXT_P1_RECALL1_THEO,
    TEXT_P1_SNATCH_SILVANUS,
    TEXT_P1_HINT_CHASE,
    TEXT_P1_CAUGHT,
    TEXT_P1_LOOTER_FLEES,
    TEXT_P1_HINT_PURSE,
    TEXT_P1_RETURN_GUIDE,
    TEXT_P1_RETURN_SILVANUS,
    TEXT_P1_RETURN_ANNA,
    TEXT_P1_THEO_FIGS,
    TEXT_P1_RECALL2_GUIDE,
    TEXT_P1_RECALL2_THEO,
    TEXT_P1_WAIT,
    TEXT_P1_WAIT_PURSE,
    TEXT_P1_FINALE,
    TEXT_P1_OUTRO,

    /* Act 1: Bouillon training yard */
    TEXT_A1_INTRO,
    TEXT_A1_INTRO_PLEDGE,
    TEXT_A1_INTRO_YARD,
    TEXT_A1_WICHER_HELLO,
    TEXT_A1_WICHER_PELLS,
    TEXT_A1_HINT_SWORD,
    TEXT_A1_PELLS_DONE,
    TEXT_A1_BALDWIN_HELLO,
    TEXT_A1_BALDWIN_GODFREY1,
    TEXT_A1_BALDWIN_SOLD,
    TEXT_A1_BALDWIN_GODFREY2,
    TEXT_A1_BALDWIN_DARE,
    TEXT_A1_HINT_DUEL,
    TEXT_A1_DUEL_LOSE,
    TEXT_A1_DUEL_LOSE_WICHER,
    TEXT_A1_DUEL_WIN,
    TEXT_A1_DUEL_WIN_WICHER,
    TEXT_A1_IDA_CALL,
    TEXT_A1_HINT_IDA,
    TEXT_A1_BLESS_GOING,
    TEXT_A1_BLESS_CROSS,
    TEXT_A1_BLESS_RIGHTLY,
    TEXT_A1_BLESS_ROAD,
    TEXT_A1_BLESS_WILL,
    TEXT_A1_BLESS_SIGN,
    TEXT_A1_OUTRO,
    TEXT_A1_OUTRO_2,

    TEXT_COUNT
};

#endif /* CRUSADE_TEXT_IDS_H */
