#!/usr/bin/env python3
"""Rasterizes UnifrakturCook (SIL OFL, graphics/src/fonts/) into C data:

  - a variable-width 1bpp glyph table for ASCII 32..126 (menus, subtitle)
  - a 1bpp "Crusade" logo bitmap

Output: graphics/gen/gothic_font.c/.h. Requires ImageMagick (`magick`).
Rerun after changing sizes:  python3 tools/gen_gothic.py
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, "graphics/src/fonts/UnifrakturCook-Bold.ttf")
OUT = os.path.join(ROOT, "graphics/gen")

GLYPH_PT = 13
LOGO_PT = 48
LOGO_TEXT = "Crusade"
SPACE_W = 4
TRACKING = 1  # blank columns after each glyph


def raster(text, pt, w, h, base):
    """Returns rows of 0/1 for `text` drawn with baseline at y=base."""
    pgm = subprocess.run(
        ["magick", "-size", f"{w}x{h}", "xc:black", "-fill", "white",
         "+antialias", "-font", FONT, "-pointsize", str(pt),
         "-annotate", f"+4+{base}", text, "-alpha", "off",
         "-colorspace", "gray", "-depth", "8", "pgm:-"],
        check=True, capture_output=True).stdout
    # P5\n<w> <h>\n255\n<data>
    parts = pgm.split(b"\n", 3)
    pw, ph = map(int, parts[1].split())
    data = parts[3]
    return [[1 if data[y * pw + x] > 127 else 0 for x in range(pw)]
            for y in range(ph)]


def col_bounds(rows):
    cols = [x for x in range(len(rows[0])) if any(r[x] for r in rows)]
    return (cols[0], cols[-1]) if cols else None


def row_bounds(rows):
    ys = [y for y, r in enumerate(rows) if any(r)]
    return (ys[0], ys[-1]) if ys else None


def gen_glyphs():
    W, H, BASE = 40, 32, 20
    glyphs = {}
    top, bot = H, 0
    for c in range(33, 127):
        rows = raster(chr(c), GLYPH_PT, W, H, BASE)
        rb = row_bounds(rows)
        if rb:
            top, bot = min(top, rb[0]), max(bot, rb[1])
        glyphs[c] = rows
    height = bot - top + 1
    assert height <= 16, f"glyph band {height}px > 16"
    out = []
    for c in range(32, 127):
        if c == 32:
            out.append((SPACE_W, [0] * height))
            continue
        rows = glyphs[c][top:bot + 1]
        cb = col_bounds(rows)
        if not cb:
            out.append((SPACE_W, [0] * height))
            continue
        x0, x1 = cb
        w = x1 - x0 + 1
        assert w <= 16, f"glyph {chr(c)!r} too wide ({w})"
        bits = []
        for r in rows:
            v = 0
            for i, x in enumerate(range(x0, x1 + 1)):
                if r[x]:
                    v |= 1 << i
            bits.append(v)
        out.append((w, bits))
    return height, BASE - top, out


def gen_logo():
    rows = raster(LOGO_TEXT, LOGO_PT, 240, 64, 44)
    y0, y1 = row_bounds(rows)
    x0, x1 = col_bounds(rows)
    rows = [r[x0:x1 + 1] for r in rows[y0:y1 + 1]]
    return rows


def main():
    gh, gbase, glyphs = gen_glyphs()
    logo = gen_logo()
    lw, lh = len(logo[0]), len(logo)
    lstride = (lw + 7) // 8

    h = f"""/* Generated by tools/gen_gothic.py from UnifrakturCook Bold
 * (SIL Open Font License 1.1, see graphics/src/fonts/OFL-UnifrakturCook.txt).
 * Do not edit by hand. */
#ifndef CRUSADE_GOTHIC_FONT_H
#define CRUSADE_GOTHIC_FONT_H

#include <tonc_types.h>

#define GOTHIC_FIRST    32
#define GOTHIC_COUNT    {len(glyphs)}
#define GOTHIC_HEIGHT   {gh}
#define GOTHIC_BASELINE {gbase}
#define GOTHIC_TRACKING {TRACKING}

/* Per-glyph width in pixels; rows are u16, bit x = pixel x. */
extern const u8  gothic_width[GOTHIC_COUNT];
extern const u16 gothic_rows[GOTHIC_COUNT][GOTHIC_HEIGHT];

#define GOTHIC_LOGO_W      {lw}
#define GOTHIC_LOGO_H      {lh}
#define GOTHIC_LOGO_STRIDE {lstride}
/* 1bpp, row-major, bit (x & 7) of byte x >> 3 = pixel x. */
extern const u8 gothic_logo[GOTHIC_LOGO_H * GOTHIC_LOGO_STRIDE];

#endif
"""
    c = ['/* Generated by tools/gen_gothic.py -- do not edit. '
         'Derived from UnifrakturCook Bold (SIL OFL 1.1). */',
         '#include "gothic_font.h"', '',
         'const u8 gothic_width[GOTHIC_COUNT] = {']
    for i in range(0, len(glyphs), 16):
        c.append("    " + ", ".join(str(w) for w, _ in glyphs[i:i + 16]) + ",")
    c.append("};\n")
    c.append("const u16 gothic_rows[GOTHIC_COUNT][GOTHIC_HEIGHT] = {")
    for i, (_, bits) in enumerate(glyphs):
        ch = chr(32 + i)
        label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
        c.append("    { " + ", ".join(f"0x{b:04X}" for b in bits)
                 + f" }}, /* {label} */")
    c.append("};\n")
    c.append("const u8 gothic_logo[GOTHIC_LOGO_H * GOTHIC_LOGO_STRIDE] = {")
    for r in logo:
        bs = []
        for bx in range(lstride):
            v = 0
            for i in range(8):
                x = bx * 8 + i
                if x < lw and r[x]:
                    v |= 1 << i
            bs.append(f"0x{v:02X}")
        c.append("    " + ", ".join(bs) + ",")
    c.append("};")

    with open(os.path.join(OUT, "gothic_font.h"), "w") as f:
        f.write(h)
    with open(os.path.join(OUT, "gothic_font.c"), "w") as f:
        f.write("\n".join(c) + "\n")
    print(f"glyph height {gh}, baseline {gbase}; logo {lw}x{lh}")
    for r in logo:
        print("".join("#" if v else "." for v in r))


if __name__ == "__main__":
    main()
