#!/usr/bin/env python3
"""Generates the opening-cinematic art (src/intro.c):

  graphics/intro_cards.png     gothic title cards     (frames: MXCV, Hierusalem)
  graphics/intro_map.png       parchment map of Christendom and the East
                               (frames: base, base + Godfrey's route)
  graphics/intro_clermont.png  Urban II preaching at Clermont
                               (frames: pointing east, arms raised)
  graphics/intro_chapel.png    Godfrey kneeling before the altar
  graphics/gen/intro_route.c/.h  map cells in route order, for the reveal

Every image is a vertical strip of 240x160 frames sharing one 16-colour
palette; only the top 112px are art (the narration box covers the rest).
grit reduces tiles across frames, so each image must stay <= 512 unique
tiles (one BG charblock) -- asserted here.

The palette indices the runtime animates are listed next to each palette
and mirrored in src/intro.c. Coastlines: Natural Earth 1:50m (public
domain), cropped copy in graphics/src/geo/.

Rerun after editing:  python3 tools/gen_intro_art.py
"""
import json
import math
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pixart import Canvas, rgb, write_png  # noqa: E402
from gen_gothic import raster, row_bounds, col_bounds  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GFX = os.path.join(ROOT, "graphics")
GEN = os.path.join(GFX, "gen")

FW, FH, ART_H = 240, 160, 112


# --- helpers -----------------------------------------------------------------

def unique_tiles(canvas):
    seen = set()
    for ty in range(canvas.h // 8):
        for tx in range(canvas.w // 8):
            t = tuple(tuple(canvas.px[ty * 8 + y][tx * 8:tx * 8 + 8])
                      for y in range(8))
            h = tuple(r[::-1] for r in t)
            v = t[::-1]
            hv = h[::-1]
            seen.add(min(t, h, v, hv))
    return len(seen)


def strip(frames):
    out = Canvas(FW, FH * len(frames))
    for i, f in enumerate(frames):
        out.blit(f, 0, i * FH)
    return out


def save(name, frames, pal, note):
    img = strip(frames)
    n = unique_tiles(img)
    assert n <= 512, f"{name}: {n} unique tiles > 512"
    assert len(pal) == 16
    write_png(os.path.join(GFX, name + ".png"), img, pal)
    with open(os.path.join(GFX, name + ".grit"), "w") as f:
        f.write(f"# {note}\n# Generated by tools/gen_intro_art.py.\n"
                "-gt -gB4 -mRtf -mLf -p -pn16\n")
    print(f"{name}.png: {len(frames)} frame(s), {n} unique tiles")
    return img


def line(c, x0, y0, x1, y1, ink):
    dx, dy = abs(x1 - x0), -abs(y1 - y0)
    sx, sy = (1 if x0 < x1 else -1), (1 if y0 < y1 else -1)
    err = dx + dy
    while True:
        c.set(x0, y0, ink)
        if x0 == x1 and y0 == y1:
            return
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x0 += sx
        if e2 <= dx:
            err += dx
            y0 += sy


def gothic(text, pt):
    """Trimmed 1bpp raster of `text` in UnifrakturCook."""
    rows = raster(text, pt, 8 * len(text) * pt // 10 + 40, pt * 2, pt * 3 // 2)
    y0, y1 = row_bounds(rows)
    x0, x1 = col_bounds(rows)
    return [r[x0:x1 + 1] for r in rows[y0:y1 + 1]]


def draw_bits(c, bits, ox, oy, ink):
    """ink: index or callable(row, col) -> index."""
    for y, r in enumerate(bits):
        for x, v in enumerate(r):
            if v:
                c.set(ox + x, oy + y, ink(y, x) if callable(ink) else ink)


# 3x5 small caps for map labels
FONT3 = {
    "A": "010101111101101", "B": "110101110101110", "C": "011100100100011",
    "D": "110101101101110", "E": "111100110100111", "F": "111100110100100",
    "G": "011100101101011", "H": "101101111101101", "I": "111010010010111",
    "J": "001001001101010", "K": "101101110101101", "L": "100100100100111",
    "M": "101111111101101", "N": "110101101101101", "O": "010101101101010",
    "P": "110101110100100", "Q": "010101101110011", "R": "110101110101101",
    "S": "011100010001110", "T": "111010010010010", "U": "101101101101111",
    "V": "101101101101010", "W": "101101111111101", "X": "101101010101101",
    "Y": "101101010010010", "Z": "111001010100111", " ": "000000000000000",
}


def text3_width(s):
    return 4 * len(s) - 1


def text3(c, s, x, y, ink):
    """ink: index or callable(x, y) -> index (so labels can adapt to what
    they are drawn over)."""
    for i, ch in enumerate(s):
        g = FONT3[ch]
        for r in range(5):
            for col in range(3):
                if g[r * 3 + col] == "1":
                    px, py = x + i * 4 + col, y + r
                    c.set(px, py, ink(px, py) if callable(ink) else ink)


# --- title cards ---------------------------------------------------------------
# 0 black  1-4 gold (dark..bright)  5-6 oxblood  7 ash
# Animated: 4 (glint) pulses.
CARD_PAL = [rgb(h) for h in (
    "000000", "4a3418", "7a5a28", "b08838", "e0c068", "3a0c0a", "6a1612",
    "2a2626", "000000", "000000", "000000", "000000", "000000", "000000",
    "000000", "000000")]


def gold_ink(h):
    def ink(y, x):
        t = y / max(1, h - 1)
        if t < 0.18:
            return 4
        if t < 0.55:
            return 3
        if t < 0.85:
            return 2
        return 1
    return ink


def jerusalem_cross(c, cx, cy):
    """Cross potent with four crosslets, 13x13, gold."""
    c.rect(cx - 1, cy - 6, cx + 2, cy + 7, 3)
    c.rect(cx - 6, cy - 1, cx + 7, cy + 2, 3)
    for ex, ey in ((cx, cy - 6), (cx, cy + 6)):
        c.rect(ex - 2, ey, ex + 3, ey + 1, 3)
    for ex, ey in ((cx - 6, cy), (cx + 6, cy)):
        c.rect(ex, ey - 2, ex + 1, ey + 3, 3)
    c.vline(cx, cy - 5, cy + 6, 4)
    c.hline(cx - 5, cx + 6, cy, 4)
    for qx, qy in ((-4, -4), (4, -4), (-4, 4), (4, 4)):
        c.vline(cx + qx, cy + qy - 1, cy + qy + 2, 2)
        c.hline(cx + qx - 1, cx + qx + 2, cy + qy, 2)


def rule(c, x0, x1, y):
    c.hline(x0, x1, y, 2)
    c.hline(x0 + 2, x1 - 2, y + 1, 5)
    for x in (x0, x1 - 1):
        c.set(x, y - 1, 1)
        c.set(x, y + 1, 1)


def ornament(c, y):
    cx = FW // 2
    rule(c, 40, cx - 12, y)
    rule(c, cx + 12, FW - 40, y)
    jerusalem_cross(c, cx, y)


def gen_cards():
    frames = []

    c = Canvas(FW, FH)
    small = gothic("Anno Domini", 16)
    big = gothic("MXCV", 36)
    sw, bw = len(small[0]), len(big[0])
    y = 18
    draw_bits(c, small, (FW - sw) // 2, y, gold_ink(len(small)))
    y += len(small) + 8
    draw_bits(c, big, (FW - bw) // 2, y, gold_ink(len(big)))
    y += len(big) + 14
    ornament(c, y)
    frames.append(c)

    c = Canvas(FW, FH)
    big = gothic("Hierusalem", 30)
    bw = len(big[0])
    ornament(c, 22)
    draw_bits(c, big, (FW - bw) // 2, 40, gold_ink(len(big)))
    ornament(c, 40 + len(big) + 14)
    frames.append(c)

    save("intro_cards", frames, CARD_PAL,
         "Opening cinematic title cards (240x160 frames, one palette).")


# --- map -----------------------------------------------------------------------
# 0 black  1 sea  2 sea lines  3 coast ink  4/5/6 land dark/mid/light
# 7/8/9 Seljuk land mid/dark/light (start = 5/4/6, runtime fades to red)
# 10/11 route red/dark  12 ink  13 pale ink (on sea)  14 gold
# 15 hidden label ink (starts = land mid, runtime fades in)
MAP_PAL = [rgb(h) for h in (
    "000000", "141c26", "26344a", "1c140e", "6a5234", "8c7450", "a8916a",
    "8c7450", "6a5234", "a8916a", "a0241a", "4a0e0a", "1e1610", "b8a888",
    "e0b850", "8c7450")]

LON0, LAT1 = -8.0, 52.5
SY = ART_H / 22.0
SX = SY * math.cos(math.radians(41.5))


def proj(lon, lat):
    return (lon - LON0) * SX, (LAT1 - lat) * SY


def unproj(x, y):
    return x / SX + LON0, LAT1 - y / SY


def scan_fill(rings, w, h):
    """Even-odd scanline fill of lon/lat rings at pixel centres."""
    mask = [[False] * w for _ in range(h)]
    edges = []
    for ring in rings:
        pts = [proj(lon, lat) for lon, lat in ring]
        for i in range(len(pts) - 1):
            (x0, y0), (x1, y1) = pts[i], pts[i + 1]
            if y0 != y1:
                edges.append((x0, y0, x1, y1))
    for y in range(h):
        yc = y + 0.5
        xs = []
        for x0, y0, x1, y1 in edges:
            if (y0 <= yc < y1) or (y1 <= yc < y0):
                xs.append(x0 + (yc - y0) * (x1 - x0) / (y1 - y0))
        xs.sort()
        for i in range(0, len(xs) - 1, 2):
            a = max(0, math.ceil(xs[i] - 0.5))
            b = min(w - 1, math.floor(xs[i + 1] - 0.5))
            for x in range(a, b + 1):
                mask[y][x] = not mask[y][x]
    return mask


# Seljuk lands c. 1095 (Rum, Syria, Palestine), lon/lat. The western edge
# runs through the Aegean and the sea; land outside stays parchment.
SELJUK_FRONTIER = [
    (25.5, 40.25), (29.4, 40.25), (29.4, 41.4), (36.0, 41.9), (41.0, 41.3),
    (43.8, 40.6), (44.6, 38.6), (43.6, 36.9), (41.6, 35.6), (40.2, 34.0),
    (38.6, 32.6), (37.2, 31.0), (35.4, 29.8), (34.3, 29.8), (34.3, 33.2),
    (25.5, 33.2),
]


def seljuk_box(lon, lat):
    inside = False
    pts = SELJUK_FRONTIER
    for (x0, y0), (x1, y1) in zip(pts, pts[1:] + pts[:1]):
        if (y0 > lat) != (y1 > lat) and \
                lon < x0 + (lat - y0) * (x1 - x0) / (y1 - y0):
            inside = not inside
    return inside


CITIES = {
    # name: (lon, lat)
    "BOUILLON": (5.07, 49.79), "CLERMONT": (3.08, 45.78),
    "ROME": (12.50, 41.90), "CONSTANTINOPLE": (28.98, 41.01),
    "MANZIKERT": (42.53, 39.14), "ANTIOCH": (36.16, 36.20),
    "JERUSALEM": (35.23, 31.78),
}
# label offsets relative to the marker
LABELS = {
    "BOUILLON": (4, -3), "CLERMONT": (-16, 4), "ROME": (-7, 4),
    "CONSTANTINOPLE": (5, -10), "MANZIKERT": (-17, -8),
    "ANTIOCH": (4, -2), "JERUSALEM": (-40, -2),
}

ROUTE = [  # Godfrey's march, 1096-1099
    (5.07, 49.79), (8.0, 49.4), (12.10, 49.02), (16.37, 48.21),
    (17.9, 47.4), (19.4, 46.3), (20.46, 44.82), (21.90, 43.32),
    (23.32, 42.70), (24.75, 42.15), (26.56, 41.68), (28.98, 41.01),
    (29.72, 40.43), (30.52, 39.78), (31.2, 38.7), (32.49, 37.87),
    (34.05, 37.51), (35.49, 38.72), (36.93, 37.58), (36.16, 36.20),
    (35.85, 34.43), (35.0, 33.0), (34.87, 31.93), (35.23, 31.78),
]

MOUNTAINS = [  # polylines (lon, lat) along which chevrons are placed
    [(6.5, 45.3), (8.5, 46.4), (11.0, 46.9), (14.0, 47.2)],          # Alps
    [(-1.5, 42.9), (2.5, 42.6)],                                       # Pyrenees
    [(10.0, 44.2), (13.0, 42.5), (15.5, 40.8)],                        # Apennines
    [(15.5, 45.2), (18.5, 43.6), (20.0, 42.0)],                        # Dinaric
    [(18.5, 49.3), (22.5, 48.8), (25.5, 47.5), (25.8, 45.6),
     (22.8, 45.4)],                                                    # Carpathians
    [(23.0, 43.0), (26.5, 42.7)],                                      # Balkan
    [(29.5, 37.2), (32.5, 36.8), (35.5, 37.3), (38.0, 37.9)],          # Taurus
    [(32.0, 41.1), (36.0, 40.9), (40.5, 40.6)],                        # Pontic
    [(38.5, 39.5), (42.5, 39.6)],                                      # Armenian
    [(40.0, 43.2), (44.0, 42.7), (48.0, 41.6)],                        # Caucasus
    [(44.5, 37.0), (47.5, 34.5), (50.5, 32.0)],                        # Zagros
    [(35.9, 33.6), (36.3, 34.6)],                                      # Lebanon
]


def catmull(points, steps=12):
    pts = [points[0]] + points + [points[-1]]
    out = []
    for i in range(1, len(pts) - 2):
        p0, p1, p2, p3 = pts[i - 1], pts[i], pts[i + 1], pts[i + 2]
        for s in range(steps):
            t = s / steps
            t2, t3 = t * t, t * t * t
            out.append(tuple(
                0.5 * (2 * p1[k] + (-p0[k] + p2[k]) * t +
                       (2 * p0[k] - 5 * p1[k] + 4 * p2[k] - p3[k]) * t2 +
                       (-p0[k] + 3 * p1[k] - 3 * p2[k] + p3[k]) * t3)
                for k in range(2)))
    out.append(points[-1])
    return out


def gen_map():
    with open(os.path.join(GFX, "src/geo/near_east_50m.json")) as f:
        geo = json.load(f)
    land = scan_fill(geo["land"], FW, ART_H)
    lake = scan_fill(geo["lakes"], FW, ART_H)
    L = [[land[y][x] and not lake[y][x] for x in range(FW)]
         for y in range(ART_H)]

    def is_land(x, y):
        return 0 <= x < FW and 0 <= y < ART_H and L[y][x]

    # Seljuk lands: inside the box and connected to Konya (drops the Aegean
    # islands and Cyprus, which stayed Byzantine).
    sel = [[False] * FW for _ in range(ART_H)]
    kx, ky = map(int, proj(32.49, 37.87))
    stack = [(kx, ky)]
    while stack:
        x, y = stack.pop()
        if not is_land(x, y) or sel[y][x]:
            continue
        if not seljuk_box(*unproj(x + 0.5, y + 0.5)):
            continue
        sel[y][x] = True
        stack += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]

    # distance from land (chebyshev, capped) for coast ink and ripple lines
    INF = 99
    dist = [[0 if L[y][x] else INF for x in range(FW)] for y in range(ART_H)]
    frontier = [(x, y) for y in range(ART_H) for x in range(FW) if L[y][x]]
    for d in range(1, 7):
        nxt = []
        for x, y in frontier:
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < FW and 0 <= ny < ART_H and dist[ny][nx] == INF:
                        dist[ny][nx] = d
                        nxt.append((nx, ny))
        frontier = nxt

    c = Canvas(FW, FH)
    for y in range(ART_H):
        for x in range(FW):
            if L[y][x]:
                edge = any(not is_land(x + dx, y + dy) and
                           0 <= x + dx < FW and 0 <= y + dy < ART_H
                           for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
                frontier = sel[y][x] and any(
                    is_land(x + dx, y + dy) and not sel[y + dy][x + dx]
                    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
                if sel[y][x]:
                    c.set(x, y, 8 if edge or frontier else 7)
                else:
                    c.set(x, y, 4 if edge else 5)
            else:
                d = dist[y][x]
                if d == 1:
                    c.set(x, y, 3)
                elif d == 3 and (x + y) % 2 == 0:
                    c.set(x, y, 2)
                else:
                    c.set(x, y, 1)
                    # engraved waves on open sea, period 16x16
                    if d > 5:
                        u, v = x % 16, y % 16
                        if (v == 4 and 3 <= u <= 5) or (v == 12 and 11 <= u <= 13):
                            c.set(x, y, 2)
                        elif (v == 3 and u == 4) or (v == 11 and u == 12):
                            c.set(x, y, 2)

    # parchment grain on open land, period 16 so the tiles repeat
    for y in range(ART_H):
        for x in range(FW):
            if c.px[y][x] in (5, 7):
                u, v = x % 16, y % 16
                if (u, v) in ((2, 3), (11, 9), (6, 13)):
                    c.set(x, y, 4 if c.px[y][x] == 5 else 8)
                elif (u, v) in ((13, 2), (5, 7)):
                    c.set(x, y, 6 if c.px[y][x] == 5 else 9)

    # mountains: little chevrons, light on the west face, dark on the east
    for chain in MOUNTAINS:
        pts = catmull([proj(*p) for p in chain], 20)
        acc, last = 0.0, None
        for p in pts:
            if last is not None:
                acc += math.hypot(p[0] - last[0], p[1] - last[1])
            last = p
            if acc < 6.0 and last is not pts[0]:
                continue
            acc = 0.0
            mx, my = int(p[0]), int(p[1])
            if not all(is_land(mx + dx, my + dy)
                       for dx in (-3, 3) for dy in (-2, 2)):
                continue
            s = sel[my][mx]
            lt, dk = (9, 8) if s else (6, 4)
            for i in range(3):
                c.set(mx - i, my - 2 + i, lt)
                c.set(mx + i, my - 2 + i, dk)
            c.set(mx + 1, my, dk)

    def label_ink(x, y):
        return 13 if not is_land(x, y) else 12

    for name, (lon, lat) in CITIES.items():
        x, y = (int(v) for v in proj(lon, lat))
        if name == "JERUSALEM":
            for dx, dy in ((0, -2), (0, -1), (0, 0), (0, 1), (0, 2),
                           (-1, -1), (1, -1)):
                c.set(x + dx, y + dy, 14)
            c.set(x - 1, y + 2, 12)
            c.set(x + 1, y + 2, 12)
        else:
            c.rect(x - 1, y - 1, x + 1, y + 1, 12)
            c.set(x + 1, y - 1, 14)
        ox, oy = LABELS[name]
        text3(c, name, x + ox, y + oy, label_ink)

    # region title revealed by palette fade (index 15)
    tx, ty = (int(v) for v in proj(31.4, 39.6))
    text3(c, "SELJUK TURKS", tx, ty, 15)
    bx, by = (int(v) for v in proj(20.0, 44.6))
    text3(c, "BYZANTIUM", bx, by, 12)

    # double rule frame
    for i, ink in ((0, 3), (1, 12), (2, 14), (3, 3)):
        c.hline(i, FW - i, i, ink)
        c.hline(i, FW - i, ART_H - 1 - i, ink)
        c.vline(i, i, ART_H - i, ink)
        c.vline(FW - 1 - i, i, ART_H - i, ink)

    # frame 1: the route, a dashed red line with a dark under-shadow
    r = Canvas(FW, FH)
    r.blit(c, 0, 0)
    path = catmull([proj(*p) for p in ROUTE], 16)
    dense = []
    for (x0, y0), (x1, y1) in zip(path, path[1:]):
        n = max(1, int(math.hypot(x1 - x0, y1 - y0) * 3))
        for i in range(n):
            t = i / n
            dense.append((x0 + (x1 - x0) * t, y0 + (y1 - y0) * t))
    dense.append(path[-1])
    acc, last, order = 0.0, None, []
    for x, y in dense:
        if last:
            acc += math.hypot(x - last[0], y - last[1])
        last = (x, y)
        px, py = int(x), int(y)
        if (acc % 6.0) < 4.0:
            if r.get(px, py + 1) not in (10,):
                r.set(px, py + 1, 11)
            r.set(px, py, 10)
        order.append((px, py))

    base, routed = c, r
    cells, seen = [], set()
    for x, y in order:
        for yy in (y, y + 1):
            cell = (yy // 8) * 30 + x // 8
            if cell in seen:
                continue
            tx_, ty_ = (cell % 30) * 8, (cell // 30) * 8
            differs = any(base.px[ty_ + j][tx_ + i] != routed.px[ty_ + j][tx_ + i]
                          for j in range(8) for i in range(8))
            if differs:
                seen.add(cell)
                cells.append(cell)
    for ty_ in range(FH // 8):
        for tx_ in range(30):
            cell = ty_ * 30 + tx_
            if cell not in seen and any(
                    base.px[ty_ * 8 + j][tx_ * 8 + i] !=
                    routed.px[ty_ * 8 + j][tx_ * 8 + i]
                    for j in range(8) for i in range(8)):
                cells.append(cell)

    save("intro_map", [base, routed], MAP_PAL,
         "Opening cinematic map (frame 0 base, frame 1 with the route).")
    write_route(cells)


def write_route(cells):
    h = ("/* Generated by tools/gen_intro_art.py -- do not edit. */\n"
         "#ifndef INTRO_ROUTE_H\n#define INTRO_ROUTE_H\n\n"
         "#include <tonc_types.h>\n\n"
         f"#define INTRO_ROUTE_CELLS {len(cells)}\n\n"
         "/* Screen cells (row*30+col) that differ between intro_map frame 0\n"
         " * and frame 1, in marching order from Bouillon to Jerusalem. */\n"
         "extern const u16 intro_routeCells[INTRO_ROUTE_CELLS];\n\n"
         "#endif\n")
    body = ",".join(str(v) for v in cells)
    cs = ("/* Generated by tools/gen_intro_art.py -- do not edit. */\n"
          '#include "intro_route.h"\n\n'
          f"const u16 intro_routeCells[INTRO_ROUTE_CELLS] = {{{body}}};\n")
    with open(os.path.join(GEN, "intro_route.h"), "w") as f:
        f.write(h)
    with open(os.path.join(GEN, "intro_route.c"), "w") as f:
        f.write(cs)


# --- shape helpers for the painted scenes ----------------------------------------

def poly(c, pts, ink):
    """Fills a pixel-space polygon (even-odd, pixel centres)."""
    ys = [p[1] for p in pts]
    for y in range(int(min(ys)), int(max(ys)) + 1):
        yc = y + 0.5
        xs = []
        for (x0, y0), (x1, y1) in zip(pts, pts[1:] + pts[:1]):
            if (y0 <= yc < y1) or (y1 <= yc < y0):
                xs.append(x0 + (yc - y0) * (x1 - x0) / (y1 - y0))
        xs.sort()
        for i in range(0, len(xs) - 1, 2):
            for x in range(math.ceil(xs[i] - 0.5), math.floor(xs[i + 1] - 0.5) + 1):
                c.set(x, y, ink)


def thick(c, x0, y0, x1, y1, ink, w=2):
    for o in range(w):
        line(c, x0 + o, y0, x1 + o, y1, ink)


def layer():
    return Canvas(FW, FH, fill=255)


def comp(dst, src, outline=None):
    """Composites a 255-keyed layer, optionally with a 1px outline."""
    if outline is not None:
        src.outline(outline, skip=(255,))
    dst.blit(src, 0, 0, key=255)


# --- Clermont, November 1095 -------------------------------------------------------
# 0 black  1-5 dusk sky (top..horizon glow)  6 hills/field  7 crowd
# 8 wood  9/10 white robe/shade  11 red  12 gold  13/14 flame/flame core
# 15 far hills.  Animated: 13/14 flicker (torches, town windows).
CLERMONT_PAL = [rgb(h) for h in (
    "000000", "141428", "2a1e38", "4a2638", "7a3428", "c06a34", "1c141c",
    "08060a", "4a3020", "d0c4a8", "8a7e6a", "8c1c13", "d8a848", "e88a30",
    "f8e0a0", "2c1e2c")]

SKY_BANDS = [(0, 1), (16, 2), (32, 3), (48, 4), (62, 5)]
HORIZON = 76


def sky(c):
    for y in range(HORIZON):
        col = 1
        for y0, ci in SKY_BANDS:
            if y >= y0:
                col = ci
        for x in range(FW):
            ink = col
            # 4-row dithered seam into the next band
            for y0, ci in SKY_BANDS[1:]:
                d = y0 - y
                if 0 < d <= 3 and (x + y) % 2 == 0 and (d < 3 or x % 4 == 0):
                    ink = ci
            c.set(x, y, ink)
    rnd = random.Random(7)
    for _ in range(26):
        x, y = rnd.randrange(FW), rnd.randrange(2, 24)
        c.set(x, y, 10 if rnd.random() < 0.7 else 9)
    # long dusk cloud streaks
    for x0, x1, y, ink in ((10, 70, 40, 4), (24, 58, 41, 2), (150, 230, 30, 3),
                           (168, 214, 31, 4), (120, 170, 52, 5),
                           (60, 104, 57, 3), (184, 236, 58, 3)):
        c.hline(x0, x1, y, ink)


def puy_de_dome(c):
    cx, base = 186, HORIZON
    for x in range(140, 240):
        dx = (x - cx) / 34.0
        h = 20 * max(0.0, 1 - dx * dx) ** 0.5 if abs(dx) < 1 else 0
        # smaller puys on either side
        for px, r, hh in ((150, 16, 9), (222, 18, 11)):
            d = (x - px) / r
            if abs(d) < 1:
                h = max(h, hh * (1 - d * d) ** 0.5)
        for y in range(int(base - h), base):
            c.set(x, y, 15)


def town(c, glow):
    # hill
    for x in range(0, 120):
        d = (x - 52) / 66.0
        h = 14 * max(0.0, 1 - d * d)
        for y in range(int(HORIZON - 2 - h), HORIZON):
            c.set(x, y, 6)
    base = HORIZON - 14
    # walls with crenels
    c.rect(18, base - 4, 92, base + 2, 6)
    for x in range(18, 92, 4):
        c.rect(x, base - 6, x + 2, base - 4, 6)
    # towers
    for tx, th in ((18, 10), (44, 8), (90, 11)):
        c.rect(tx - 2, base - th, tx + 3, base, 6)
        c.rect(tx - 3, base - th - 2, tx + 4, base - th, 6)
    # cathedral: nave, transept, twin west towers with spires
    c.rect(52, base - 12, 82, base, 6)
    poly(c, [(51, base - 12), (83, base - 12), (67, base - 18)], 6)
    for sx in (54, 62):
        c.rect(sx, base - 22, sx + 5, base, 6)
        poly(c, [(sx - 0.5, base - 22), (sx + 5.5, base - 22), (sx + 2.5, base - 32)], 6)
    c.vline(76, base - 22, base - 12, 6)
    c.hline(74, 79, base - 20, 6)
    # houses
    for hx, hw, hh in ((24, 7, 7), (32, 6, 9), (39, 5, 6), (86, 6, 7), (96, 8, 5)):
        c.rect(hx, base - hh, hx + hw, base, 6)
        poly(c, [(hx - 1, base - hh), (hx + hw + 1, base - hh),
                 (hx + hw / 2, base - hh - 4)], 6)
    for wx, wy in ((26, -4), (34, -6), (57, -16), (65, -9), (69, -9),
                   (88, -4), (99, -3), (41, -3)):
        c.set(wx, base + wy, glow)


def person(c, x, y, rnd, style):
    """Back-view crowd figure; (x, y) = top of head."""
    poly(c, [(x - 6, y + 10), (x + 7, y + 10), (x + 9, y + 30), (x - 8, y + 30)], 7)
    c.ellipse(x + 0.5, y + 8, 6.5, 3.5, 7)
    c.ellipse(x + 0.5, y + 3.5, 3, 3.5, 7)
    if style == 0:      # conical helm with nasal
        poly(c, [(x - 3, y + 2), (x + 4, y + 2), (x + 0.5, y - 3)], 7)
    elif style == 1:    # hood
        poly(c, [(x - 4, y + 7), (x - 3, y), (x + 4, y), (x + 5, y + 7)], 7)
    elif style == 2:    # bare / cap
        c.rect(x - 2, y, x + 3, y + 1, 7)


def gen_clermont():
    frames = []
    rnd = random.Random(1095)
    crowd_spec = []
    for row, (y, n) in enumerate(((84, 20), (92, 17), (101, 14))):
        for i in range(n):
            x = int((i + 0.5) * FW / n + rnd.randint(-4, 4))
            if row == 0 and 88 <= x <= 152:
                continue
            crowd_spec.append((row, x, y + rnd.randint(-2, 2),
                               rnd.randrange(3), rnd.random()))

    for raised in (False, True):
        c = Canvas(FW, FH)
        sky(c)
        puy_de_dome(c)
        town(c, 13)
        c.rect(0, HORIZON, FW, ART_H, 6)

        # platform
        px0, px1, ptop = 92, 148, 74
        c.rect(px0, ptop, px1, ptop + 4, 8)
        c.hline(px0, px1, ptop, 12)
        poly(c, [(px0, ptop + 4), (px1, ptop + 4), (px1 - 2, ptop + 18),
                 (px0 + 2, ptop + 18)], 11)
        for x in range(px0 + 6, px1 - 4, 8):
            c.vline(x, ptop + 5, ptop + 17, 7)
        c.hline(px0 + 1, px1 - 1, ptop + 4, 12)

        # processional cross held by a cleric on the left of the platform
        cl = layer()
        poly(cl, [(101, ptop - 16), (107, ptop - 16), (109, ptop), (99, ptop)], 7)
        cl.ellipse(104, ptop - 18, 2.5, 3, 7)
        comp(c, cl)
        c.vline(109, ptop - 40, ptop, 8)
        c.rect(105, ptop - 36, 114, ptop - 34, 12)
        c.rect(108, ptop - 42, 111, ptop - 28, 12)
        c.set(109, ptop - 41, 14)
        # banner on the right
        c.vline(140, ptop - 38, ptop, 8)
        poly(c, [(141, ptop - 37), (153, ptop - 37), (153, ptop - 22),
                 (147, ptop - 25), (141, ptop - 22)], 11)
        c.vline(147, ptop - 35, ptop - 26, 12)
        c.hline(144, 151, ptop - 32, 12)

        # Urban II
        u = layer()
        cx, top = 122, ptop - 30
        poly(u, [(cx - 4, top + 10), (cx + 5, top + 10), (cx + 8, top + 30),
                 (cx - 7, top + 30)], 9)
        poly(u, [(cx + 2, top + 12), (cx + 5, top + 10), (cx + 8, top + 30),
                 (cx + 4, top + 30)], 10)
        poly(u, [(cx - 5, top + 9), (cx + 6, top + 9), (cx + 7, top + 15),
                 (cx - 6, top + 15)], 11)
        u.vline(cx, top + 12, top + 30, 12)
        u.hline(cx - 2, cx + 3, top + 13, 12)
        u.ellipse(cx + 0.5, top + 7, 2.5, 3, 7)
        poly(u, [(cx - 3, top + 5), (cx + 4, top + 5), (cx + 3, top),
                 (cx + 0.5, top - 3), (cx - 2, top)], 9)
        u.hline(cx - 2, cx + 3, top + 4, 12)
        u.vline(cx, top - 1, top + 4, 12)
        if raised:
            thick(u, cx - 5, top + 11, cx - 9, top + 1, 9)
            thick(u, cx + 5, top + 11, cx + 8, top + 1, 9)
            u.rect(cx - 10, top - 1, cx - 7, top + 1, 7)
            u.rect(cx + 8, top - 1, cx + 11, top + 1, 7)
        else:
            thick(u, cx + 5, top + 11, cx + 14, top + 4, 9)
            u.rect(cx + 14, top + 3, cx + 17, top + 5, 7)
            thick(u, cx - 5, top + 11, cx - 6, top + 19, 9)
        comp(c, u, outline=0)

        # crowd, back rows first; every figure is a dark silhouette
        cr = layer()
        torches = []
        for row, x, y, style, r in crowd_spec:
            person(cr, x, y, rnd, style)
            arm = raised and r < 0.55
            if r > 0.9:                       # torch bearer
                h = 14
                cr.vline(x + 6, y - h, y + 10, 7)
                torches.append((x + 6, y - h))
            elif r > 0.75:                    # spear
                h = 24 if raised else 18
                cr.vline(x - 5, y - h, y + 12, 7)
                cr.set(x - 5, y - h - 1, 10)
                cr.set(x - 5, y - h - 2, 10)
            elif r > 0.68:                    # cross on a staff
                cr.vline(x + 5, y - 14, y + 10, 7)
                cr.hline(x + 3, x + 8, y - 11, 7)
            if arm:
                side = -1 if r < 0.3 else 1
                sx = x + side * 5
                thick(cr, sx, y + 9, sx + side * 2, y - 4, 7)
                cr.rect(sx + side * 2 - 1, y - 6, sx + side * 2 + 2, y - 3, 7)
                if r < 0.12:                  # sword brandished
                    cr.vline(sx + side * 2, y - 16, y - 6, 10)
                    cr.hline(sx + side * 2 - 2, sx + side * 2 + 3, y - 7, 12)
        # rim light from the western glow on top edges
        src = [row_[:] for row_ in cr.px]
        for y in range(FH):
            for x in range(FW):
                if src[y][x] == 7 and y > 0 and src[y - 1][x] == 255 and \
                        (x + y) % 3 != 0:
                    cr.px[y][x] = 4
        comp(c, cr)
        for tx, ty in torches:
            c.rect(tx - 1, ty - 3, tx + 2, ty, 13)
            c.set(tx, ty - 4, 13)
            c.set(tx, ty - 2, 14)
            c.set(tx, ty - 1, 14)
        c.rect(0, ART_H, FW, FH, 0)
        frames.append(c)

    save("intro_clermont", frames, CLERMONT_PAL,
         "Opening cinematic: Urban II at Clermont (frame 1: arms raised).")


# --- the chapel: Godfrey takes the cross ---------------------------------------
# 0 black  1/2/3 stone dark/mid/lit  4 lead  5/6/7/8 glass blue/red/gold/green
# 9 window light  10/11 mail dark/light  12 surcoat  13 flame  14 wax/linen
# 15 candle-lit stone.  Animated: 13 + 15 flicker, 5-8 slow glow.
CHAPEL_PAL = [rgb(h) for h in (
    "000000", "0c0a10", "1a1620", "2a2430", "050405", "2a4890", "9a2016",
    "d0a040", "2e6040", "3e3850", "34363e", "7c808c", "5a1410", "f0a040",
    "e0d4b8", "4a3024")]

FLOOR_Y = 96


def stone_wall(c):
    for y in range(ART_H):
        for x in range(FW):
            row = y // 8
            off = 8 if row % 2 else 0
            mortar = y % 8 == 7 or (x + off) % 16 == 15
            c.set(x, y, 1 if mortar else 2)
    # floor flagstones
    for y in range(FLOOR_Y, ART_H):
        for x in range(FW):
            k = y - FLOOR_Y
            seam = k in (0, 5, 11) or ((x + k * 2) % 24 == 0 and k > 0)
            c.set(x, y, 1 if seam else 2)


def window(c, cx, top, w, h):
    x0, x1 = cx - w // 2, cx + w // 2
    arch = w // 2

    def inside(x, y):
        if y >= top + arch:
            return x0 <= x < x1
        # pointed arch: intersection of two circles radius w centred on the
        # opposite springers
        dy = (top + arch) - y
        return ((x - x0) ** 2 + dy ** 2 <= w * w and
                (x - x1 + 1) ** 2 + dy ** 2 <= w * w and x0 <= x < x1)

    for y in range(top - 2, top + h + 3):
        for x in range(x0 - 3, x1 + 3):
            near = any(inside(x + dx, y + dy) for dx in (-3, 0, 3) for dy in (-3, 0, 3))
            if near and not inside(x, y):
                c.set(x, y, 3)
    for y in range(top, top + h):
        for x in range(x0, x1):
            if not inside(x, y):
                continue
            lx, ly = x - x0, y - top
            # cross in gold on blue, border of red, lead lines
            mid = w // 2
            if abs(lx - mid) <= 1 and 8 <= ly <= h - 8 or \
                    abs(ly - (arch + 6)) <= 1 and 6 <= lx <= w - 7:
                ink = 7
            elif lx < 3 or lx >= w - 3 or ly >= h - 3:
                ink = 6 if (ly // 4) % 2 == 0 else 5
            elif (lx + ly) % 9 < 1 or (lx - ly) % 9 < 1:
                ink = 4
            else:
                ink = 5 if ((lx // 5 + ly // 6) % 3) else 8
            if lx in (2, w - 3) or ly == h - 3 or ly == arch + 2 and lx > 2 and lx < w - 3:
                ink = 4
            c.set(x, y, ink)
    c.rect(x0 - 4, top + h, x1 + 4, top + h + 2, 3)


def shaft(c, top_l, top_r, bot_l, bot_r, y0, y1):
    for y in range(y0, y1):
        t = (y - y0) / (y1 - y0)
        xl = top_l + (bot_l - top_l) * t
        xr = top_r + (bot_r - top_r) * t
        for x in range(int(xl), int(xr)):
            if c.get(x, y) in (1, 2) and (x + y) % 2 == 0:
                c.set(x, y, 9 if c.get(x, y) == 2 else 3)


def candle(c, x, y, tall):
    c.rect(x - 1, y - tall, x + 1, y, 14)
    c.set(x, y - tall - 1, 13)
    c.set(x, y - tall - 2, 13)
    c.set(x - 1, y - tall - 1, 13)
    c.rect(x - 2, y, x + 2, y + 1, 7)
    c.vline(x, y + 1, y + 5, 7)
    c.rect(x - 2, y + 5, x + 3, y + 6, 7)


def halo(c, cx, cy, r):
    for y in range(cy - r, cy + r + 1):
        for x in range(cx - r, cx + r + 1):
            d = math.hypot(x - cx, y - cy)
            if d > r or c.get(x, y) not in (1, 2, 3, 9):
                continue
            if d < r * 0.5 or (d < r * 0.85 and (x + y) % 2 == 0):
                c.set(x, y, 15)


def godfrey(fx, fy):
    """Kneeling knight facing right; (fx, fy) = front knee on the floor."""
    g = layer()
    # cloak down his back
    poly(g, [(fx - 8, fy - 24), (fx - 3, fy - 24), (fx - 4, fy - 10),
             (fx - 16, fy), (fx - 6, fy)], 1)
    # back leg kneeling: shin flat on the floor
    thick(g, fx - 14, fy - 1, fx - 4, fy - 1, 10, 1)
    g.rect(fx - 14, fy - 3, fx - 4, fy, 10)
    # front leg: thigh forward, shin down
    poly(g, [(fx - 8, fy - 13), (fx + 1, fy - 12), (fx + 2, fy - 8), (fx - 7, fy - 7)], 10)
    g.rect(fx - 1, fy - 9, fx + 3, fy, 10)
    g.rect(fx - 1, fy - 1, fx + 5, fy, 10)
    # torso in mail, leaning toward the sword
    poly(g, [(fx - 9, fy - 12), (fx - 2, fy - 12), (fx + 1, fy - 24),
             (fx - 6, fy - 25)], 11)
    poly(g, [(fx - 4, fy - 25), (fx + 1, fy - 24), (fx - 2, fy - 12),
             (fx - 5, fy - 12)], 10)
    # surcoat skirt over the thighs, cross on the chest
    poly(g, [(fx - 9, fy - 15), (fx - 1, fy - 15), (fx + 2, fy - 7),
             (fx - 9, fy - 6)], 12)
    poly(g, [(fx - 8, fy - 23), (fx - 1, fy - 23), (fx - 2, fy - 15),
             (fx - 9, fy - 15)], 12)
    g.vline(fx - 5, fy - 22, fy - 16, 14)
    g.hline(fx - 7, fx - 2, fy - 20, 14)
    # head bowed: mail coif, face lost in shadow
    g.ellipse(fx + 1, fy - 26, 3.5, 3.5, 11)
    g.rect(fx + 2, fy - 26, fx + 5, fy - 23, 1)
    g.set(fx + 4, fy - 25, 10)
    # arms reaching to the hilt
    thick(g, fx - 1, fy - 22, fx + 6, fy - 17, 10)
    # sword planted point-down: the hilt makes the cross
    sx = fx + 8
    g.vline(sx, fy - 15, fy + 1, 11)
    g.vline(sx + 1, fy - 15, fy, 10)
    g.rect(sx - 3, fy - 17, sx + 5, fy - 15, 7)
    g.vline(sx, fy - 22, fy - 17, 12)
    g.vline(sx + 1, fy - 22, fy - 17, 12)
    g.rect(sx - 1, fy - 24, sx + 3, fy - 22, 7)
    g.rect(sx - 1, fy - 20, sx + 2, fy - 17, 14 if False else 11)
    return g


def gen_chapel():
    c = Canvas(FW, FH)
    stone_wall(c)
    # columns
    for px in (24, 208):
        c.rect(px, 0, px + 12, FLOOR_Y, 3)
        c.vline(px, 0, FLOOR_Y, 1)
        c.vline(px + 11, 0, FLOOR_Y, 1)
        c.vline(px + 3, 0, FLOOR_Y, 2)
        c.rect(px - 2, 18, px + 14, 22, 3)
        c.hline(px - 2, px + 14, 22, 1)
        c.rect(px - 2, FLOOR_Y - 4, px + 14, FLOOR_Y, 3)
    window(c, 120, 8, 28, 56)
    shaft(c, 106, 134, 82, 118, 66, FLOOR_Y + 8)
    # altar
    ax0, ax1, atop = 150, 194, 80
    c.rect(ax0, atop, ax1, FLOOR_Y, 3)
    c.rect(ax0 - 2, atop - 2, ax1 + 2, atop, 14)
    c.rect(ax0 + 4, atop, ax1 - 4, FLOOR_Y - 2, 6)
    c.vline(ax0 + 4, atop, FLOOR_Y - 2, 7)
    c.vline(ax1 - 5, atop, FLOOR_Y - 2, 7)
    c.vline((ax0 + ax1) // 2, atop + 2, FLOOR_Y - 5, 7)
    c.hline((ax0 + ax1) // 2 - 3, (ax0 + ax1) // 2 + 4, atop + 5, 7)
    # altar cross and candles
    acx = (ax0 + ax1) // 2
    c.rect(acx - 1, atop - 20, acx + 1, atop - 2, 7)
    c.rect(acx - 5, atop - 16, acx + 6, atop - 14, 7)
    c.rect(acx - 3, atop - 4, acx + 4, atop - 2, 7)
    for x in (ax0 + 4, ax1 - 5):
        halo(c, x, atop - 18, 13)
    for x in (ax0 + 4, ax1 - 5):
        candle(c, x, atop - 8, 8)
    comp(c, godfrey(98, FLOOR_Y + 4), outline=0)
    c.rect(0, ART_H, FW, FH, 0)
    save("intro_chapel", [c], CHAPEL_PAL,
         "Opening cinematic: Godfrey kneels in the chapel at Bouillon.")


def main():
    gen_cards()
    gen_map()
    gen_clermont()
    gen_chapel()


if __name__ == "__main__":
    main()
