#include <tonc.h>
#include <maxmod.h>
#include "audio.h"

/* The soundbank is generated by mmutil from the audio directory's tracker
 * modules into build/soundbank.bin + build/soundbank.h (see Makefile
 * MUSIC/AUDIOFILES). Until real leitmotif modules exist in audio/, this
 * translation unit compiles standalone and audio_init() just skips mmInit
 * if the generated soundbank header hasn't been produced yet. */
#if __has_include("soundbank.h")
#include "soundbank.h"
#define HAVE_SOUNDBANK 1
#else
#define HAVE_SOUNDBANK 0
#endif

static BOOL s_audioReady = FALSE;

void audio_init(void) {
#if HAVE_SOUNDBANK
    mmInitDefault((mm_addr)soundbank_bin, 8);
    s_audioReady = TRUE;
#endif
}

void audio_play_bgm(u16 moduleId) {
    if (!s_audioReady || moduleId == AUDIO_BGM_NONE) {
        return;
    }
#if HAVE_SOUNDBANK
    mmStart(moduleId, MM_PLAY_LOOP);
#else
    (void)moduleId;
#endif
}

void audio_frame_update(void) {
    if (s_audioReady) {
        mmFrame();
    }
}
